const ar = {
  setting: 'الضبط',
  language: 'اللغة',
  arabic: 'العربية',
  english: 'الانجليزية',
  weight: 'الوزن',
  kg: 'كغم',
  lbs: 'باوند',
  distance: 'المسافة',
  feet: 'قدم',
  meters: 'متر',
  launch: 'اطلاق',
  'launch year': 'سنة الاطلاق',
  'rocket core': 'محتوى الصاروخ',
  'flright number': 'رقم الطيران',
  'rocket firing': 'اطلاق الصواريخ',
  'rocket name': 'اسم الصاروخ',
  lanching: 'الانطلاق',
  landing: 'الهبوط',
  rused: 'خادع',
  'not rused': 'غير خادع',
  success: 'نجح',
  fail: 'فشل',
  missions: 'البعثات',
};
export default ar;
