const en = {
  setting: 'Setting',
  language: 'Language',
  arabic: 'Arabic',
  english: 'English',
  weight: 'Weight',
  kg: 'kg',
  lbs: 'lbs',
  distance: 'Distance',
  feet: 'feet',
  meters: 'meters',
  launch: 'Lanuch',
  'launch year': 'Launch Year',
  'rocket core': 'Rocket Core',
  'flight number': 'Flight Number',
  'rocket firing': 'Rocket Firing',
  'rocket name': 'Rocket Name',
  lanching: 'Lanching',
  landing: 'Landing',
  rused: 'Rused',
  'not rused': 'Not Rused',
  success: 'Success',
  fail: 'Fail',
  missions: 'Missions',
};
export default en;
